### ISSUE TITLE
No web processes running. No `Procfile `

### ISSUE THREAD

**Issue by polinom** [agconti/cookiecutter-django-rest#556] opened 2018-02-19 18:13 UTC
After I deployed app to the heroku, webproccess is not running. 

I'm not using github, so not travic-ci for me. Does it hardly depends on travic-ci ? Also I don't see `Procfile `?

`heroku logs` gives this:

```
2018-02-19T18:01:34.000000+00:00 app[api]: Build started by user polino@g.com
2018-02-19T18:02:43.010675+00:00 app[api]: Deploy dc9286c6 by user polino@g.com
2018-02-19T18:02:43.010675+00:00 app[api]: Release v6 created by user polino@g.com
2018-02-19T18:01:34.000000+00:00 app[api]: Build succeeded
2018-02-19T18:02:53.232690+00:00 heroku[router]: at=error code=H14 desc="No web processes running" method=GET path="/" host=luken-backend-prod.herokuapp.com request_id=6c81d82c-4a01-4cab-a182-9d455863a7cc fwd="70.48.32.118" dyno= connect= service= status=503 bytes= protocol=https
2018-02-19T18:02:53.511132+00:00 heroku[router]: at=error code=H14 desc="No web processes running" method=GET path="/robots.txt" host=luken-backend-prod.herokuapp.com request_id=6625717b-a4df-42bc-b592-cadee2078cfb fwd="70.48.32.118" dyno= connect= service= status=503 bytes= protocol=https
2018-02-19T18:02:53.667990+00:00 heroku[router]: at=error code=H14 desc="No web processes running" method=GET path="/robots.txt" host=luken-backend-prod.herokuapp.com request_id=7735ea3f-8fe8-4d70-a360-bc81697da8ac fwd="70.48.32.118" dyno= connect= service= status=503 bytes= protocol=https
2018-02-19T18:02:55.372984+00:00 heroku[router]: at=error code=H14 desc="No web processes running" method=GET path="/robots.txt" host=luken-backend-prod.herokuapp.com request_id=aa53d84a-e067-4a0f-97e8-bda0770f9f3e fwd="70.48.32.118" dyno= connect= service= status=503 bytes= protocol=https
2018-02-19T18:02:56.545073+00:00 heroku[router]: at=error code=H14 desc="No web processes running" method=GET path="/favicon.ico" host=luken-backend-prod.herokuapp.com request_id=88720e03-e77b-46c6-a021-dc81facea244 fwd="70.48.32.118" dyno= connect= service= status=503 bytes= protocol=https
2018-02-19T18:05:51.839694+00:00 heroku[router]: at=error code=H14 desc="No web processes running" method=GET path="/" host=luken-backend-prod.herokuapp.com request_id=18ba6eb7-0c27-4db9-a52a-9d77ca2206da fwd="70.48.32.118" dyno= connect= service= status=503 bytes= protocol=https
2018-02-19T18:05:51.856787+00:00 heroku[router]: at=error code=H14 desc="No web processes running" method=GET path="/robots.txt" host=luken-backend-prod.herokuapp.com request_id=ff0fa663-fb46-49ca-9f55-c8c11763153c fwd="70.48.32.118" dyno= connect= service= status=503 bytes= protocol=https
2018-02-19T18:05:52.335208+00:00 heroku[router]: at=error code=H14 desc="No web processes running" method=GET path="/robots.txt" host=luken-backend-prod.herokuapp.com request_id=4228247b-a8f7-4fe7-98f0-763725fa6814 fwd="70.48.32.118" dyno= connect= service= status=503 bytes= protocol=https
2018-02-19T18:05:54.052192+00:00 heroku[router]: at=error code=H14 desc="No web processes running" method=GET path="/favicon.ico" host=luken-backend-prod.herokuapp.com request_id=1f83ec7b-91ef-4e51-af8b-3dedba29b30f fwd="70.48.32.118" dyno= connect= service= status=503 bytes= protocol=https
2018-02-19T18:05:53.948219+00:00 heroku[router]: at=error code=H14 desc="No web processes running" method=GET path="/robots.txt" host=luken-backend-prod.herokuapp.com request_id=39cf44e3-5a2a-4ad4-98c9-6328942647f2 fwd="70.48.32.118" dyno= connect= service= status=503 bytes= protocol=https
```

**Comment by agconti** [comment] 2018-02-19 19:49
@polinom thanks for opening up an issue ✨ 

The project:

- doesn't have a hard dependency on travis 
- doesn't use a Procfile to deploy to Heroku

It uses Heroku's [container registry and runtime](https://devcenter.heroku.com/articles/container-registry-and-runtime) rather then slug based Procfile one.  Instead of using a Procfile, you create an image of your project using a Dockerfile. The `CMD` statement in that Dockerfile defines how the project runs once its pushed to Heroku. Its analogue in a Procfile are the web and worker statements. 

To create these containers, you can use whatever CI platform you want, or even build them by hand. They just need to be pushed to Heroku's container registry after they're built so Heroku can deploy your project.

Check out [Heroku's docs](https://devcenter.heroku.com/articles/container-registry-and-runtime#getting-started) on building and deploying containers by hand and with ci for more info.

**Comment by agconti** [comment] 2018-02-19 19:52
I'm going to close this since its not a bug for the project. Feel free to reach out if you run into any issues with the project itself. ✨💖

**Comment by polinom** [comment] 2018-02-19 19:53
thanks @agconti for complete and clear answer. So just one last question. Is the image used in this project already deployed on heroku registry?

**Closed as completed by agconti** 2018-02-19 19:52 UTC

**Comment by agconti** [comment] 2018-02-19 20:00
@polinom 'course! 

The image you'll create is unique to your project. There isn't a generic or base image from this project thats already pushed to Heroku.

**Comment by polinom** [comment] 2018-02-20 00:04
Thanks @agconti. I guess we have add this manual to README. I could not figure out how to deploy application to heroku without this info.

**Comment by Foneti** [comment] 2022-06-24 16:58
help me pls
